# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import chat_pb2 as proto_dot_chat__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Chat service for client-server communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinChat = channel.unary_stream(
                '/chat.ChatService/JoinChat',
                request_serializer=proto_dot_chat__pb2.JoinRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/chat.ChatService/SendMessage',
                request_serializer=proto_dot_chat__pb2.ChatMessage.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.SendResponse.FromString,
                _registered_method=True)
        self.GetServerStatus = channel.unary_unary(
                '/chat.ChatService/GetServerStatus',
                request_serializer=proto_dot_chat__pb2.StatusRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.ServerStatus.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/chat.ChatService/Ping',
                request_serializer=proto_dot_chat__pb2.PingRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.PingResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Chat service for client-server communication
    """

    def JoinChat(self, request, context):
        """Stream for receiving messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Send a message to the chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerStatus(self, request, context):
        """Get server status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinChat': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinChat,
                    request_deserializer=proto_dot_chat__pb2.JoinRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.ChatMessage.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=proto_dot_chat__pb2.ChatMessage.FromString,
                    response_serializer=proto_dot_chat__pb2.SendResponse.SerializeToString,
            ),
            'GetServerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerStatus,
                    request_deserializer=proto_dot_chat__pb2.StatusRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.ServerStatus.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=proto_dot_chat__pb2.PingRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Chat service for client-server communication
    """

    @staticmethod
    def JoinChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat.ChatService/JoinChat',
            proto_dot_chat__pb2.JoinRequest.SerializeToString,
            proto_dot_chat__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/SendMessage',
            proto_dot_chat__pb2.ChatMessage.SerializeToString,
            proto_dot_chat__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/GetServerStatus',
            proto_dot_chat__pb2.StatusRequest.SerializeToString,
            proto_dot_chat__pb2.ServerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/Ping',
            proto_dot_chat__pb2.PingRequest.SerializeToString,
            proto_dot_chat__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RaftServiceStub(object):
    """RAFT service for server-server communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/chat.RaftService/RequestVote',
                request_serializer=proto_dot_chat__pb2.VoteRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/chat.RaftService/AppendEntries',
                request_serializer=proto_dot_chat__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)
        self.RedirectToLeader = channel.unary_unary(
                '/chat.RaftService/RedirectToLeader',
                request_serializer=proto_dot_chat__pb2.RedirectRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.RedirectResponse.FromString,
                _registered_method=True)


class RaftServiceServicer(object):
    """RAFT service for server-server communication
    """

    def RequestVote(self, request, context):
        """Request vote from other servers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Append log entries (also used as heartbeat)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RedirectToLeader(self, request, context):
        """Redirect client to leader
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=proto_dot_chat__pb2.VoteRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=proto_dot_chat__pb2.AppendEntriesRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'RedirectToLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.RedirectToLeader,
                    request_deserializer=proto_dot_chat__pb2.RedirectRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.RedirectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.RaftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaftService(object):
    """RAFT service for server-server communication
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.RaftService/RequestVote',
            proto_dot_chat__pb2.VoteRequest.SerializeToString,
            proto_dot_chat__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.RaftService/AppendEntries',
            proto_dot_chat__pb2.AppendEntriesRequest.SerializeToString,
            proto_dot_chat__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RedirectToLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.RaftService/RedirectToLeader',
            proto_dot_chat__pb2.RedirectRequest.SerializeToString,
            proto_dot_chat__pb2.RedirectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DNSServiceStub(object):
    """DNS service for service discovery
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/chat.DNSService/Lookup',
                request_serializer=proto_dot_chat__pb2.LookupRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/chat.DNSService/Register',
                request_serializer=proto_dot_chat__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.RegisterResponse.FromString,
                _registered_method=True)


class DNSServiceServicer(object):
    """DNS service for service discovery
    """

    def Lookup(self, request, context):
        """Lookup server by name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Register server in DNS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DNSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=proto_dot_chat__pb2.LookupRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.LookupResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=proto_dot_chat__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.DNSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.DNSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DNSService(object):
    """DNS service for service discovery
    """

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.DNSService/Lookup',
            proto_dot_chat__pb2.LookupRequest.SerializeToString,
            proto_dot_chat__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.DNSService/Register',
            proto_dot_chat__pb2.RegisterRequest.SerializeToString,
            proto_dot_chat__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
